Use kafka producer properly
Calling producer.poll() is required or producer will fail with:

    BufferError: Local: Queue full, instance_id: ...

Add 'extra_config' parameter to extend configuration of the kafka producer

Update tests/docs

Change-Id: I8f17437c0c24d61a6f3be5de3d4004c21fcad75a